# Number of replicas for dev
replicaCount: 1

# Application image (Python app)
image:
  repository: anupam0307/app
  tag: ""
  pullPolicy: IfNotPresent

# Container port (what your Python app listens on)
containerPort: 8000

# Service configuration (internal only)
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

# Environment variables
env:
  ENV: dev

# Resources (free-tier safe)
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

# Service account for IRSA
serviceAccount:
  name: app-sa

# IRSA configuration (Secrets Manager access)
irsa:
  roleArn: arn:aws:iam::<ACCOUNT_ID>:role/eks-secrets-reader-dev
