apiVersion: v1
kind: Service
metadata:
  name: node-svc
spec:
  type: LoadBalancer
  selector:
    app: node
  ports:
  - port: 80          # Exposing port 80 of service (LB)
    targetPort: 3000  # Forwarding to port 3000 of the pod
