name: Build and Push App Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: anupam0307/app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG app/

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update Helm values (dev)
        run: |
          sed -i "s/tag:.*/tag: $IMAGE_TAG/" helm/app/values-dev.yaml

      - name: Commit image update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add helm/app/values-dev.yaml
          git commit -m "Update dev image to $IMAGE_TAG"
          git push
