global:
  resolve_timeout: 5m

route:
  receiver: "default-receiver"
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: "default-receiver"
    email_configs:
      - to: "your-email@example.com"
        from: "alertmanager@example.com"
        smarthost: "smtp.gmail.com:587"
        auth_username: "your-email@example.com"
        auth_password: "your-app-password"
        send_resolved: true
