global:
  scrape_interval: 15s
  evaluation_interval: 15s

# --------------------
# Alertmanager config
# --------------------
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# --------------------
# Alert rules
# --------------------
rule_files:
  - /etc/prometheus/alert-rules.yml

# --------------------
# Scrape targets
# --------------------
scrape_configs:
  - job_name: "node-app"
    static_configs:
      - targets: ["app:3000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

