name: Project4 CI - Build & Push App Image

on:
  push:
    branches:
      - main
    paths:
      - "Project4-Domain/app/**"
      - ".github/workflows/project4.yaml"
  workflow_dispatch:

permissions:
  contents: write

env:
  IMAGE_NAME: anupam0307/app
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:$IMAGE_TAG \
            Project4-Domain/app

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update image tag in Helm values
        run: |
          sed -i "s/tag:.*/tag: ${{ github.sha }}/" helm/app/values-dev.yaml

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add helm/app/values-dev.yaml
          git diff --cached --quiet || git commit -m "Update app image to ${{ github.sha }} [skip ci]"
          git push
