name: Docker CI with Trivy

on:
  push:
    branches:
      - main
    paths:
      - "Multi-Stage-Docker-Monitoring/**"
  workflow_dispatch:


jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
           -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Image
      run: docker build -t anupam0307/docker-prod-app:${{ github.sha }} app/

    - name: Trivy Scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: anupam0307/docker-prod-app:${{ github.sha }}
        severity: CRITICAL
        exit-code: 1
        ignore-unfixed: true

    - name: Push Image
      run: docker push anupam0307/docker-prod-app:${{ github.sha }}
